language: java

# node_js comes pre-installed in every travis-ci box...
env:
  - TRAVIS_NODE_VERSION="4"

install:
  - cd apt-graph && mvn --quiet install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
  - cd ../website && npm install
  
before_script:
  - npm install grunt-cli -g

script:
  - cd ../apt-graph && mvn clean install -Dmaven.javadoc.skip=true -Dgpg.skip=true
  - cd ../website && grunt

#after_success:
#  - mvn clean cobertura:cobertura coveralls:report
